blank_issues_enabled: false
contact_links:
  - name: Troubleshooting & Feature Proposals
    url: https://github.com/orgs/okd-project/discussions
    about: Please use Discussions to troubleshoot issues and propose features
  - name: Security Team
    url: https://access.redhat.com/site/security/team/contact/
    about: Please report security vulnerabilities here.
  - name: Slack chat
    url: https://app.slack.com/client/T09NY5SBT/C6AD6JM17
    about: openshift-users chat room
